project:
  type: website
  output-dir: docs
  resources:
    - img/
    - css/
    - slides/


website:
  title: "Introduction to single-cell RNA-seq"
  page-footer: >
      This lesson has been developed by members of the teaching team at the [Harvard Chan Bioinformatics Core (HBC)](http://bioinformatics.sph.harvard.edu/). <br>
      These are open access materials distributed under the terms of the [Creative Commons Attribution license](https://creativecommons.org/licenses/by/4.0/) (CC BY 4.0), which permits unrestricted use, distribution, and reproduction in any medium, provided the original author and source are credited.

  
  navbar:
    left:
      - text: "Schedule"
        href: schedule/schedule.qmd
    right:
      - text: "HBC"
        href: https://bioinformatics.sph.harvard.edu/
      - text: "GitHub"
        href: https://github.com/hbctraining/Intro-to-spatial-scRNA-seq
      - text: "Contact us"
        href: mailto:hbctraining@hsph.harvard.edu
  
  
  sidebar:
    title: "Lessons"      # Optional title above the sidebar
    style: "docked"       # Sidebar is docked to the left
    collapse-level: 1     # At what header level to start collapsing
    # contents: auto      # Creates automatic TOC from page headers (no sections)
    contents:
      - section: "Pre-reading:"
        contents:
        - lessons/Pre-reading_01.qmd
        - lessons/Pre-reading_02.qmd
        - lessons/Pre-reading_03.qmd

      - section: "Day 1:"
        contents:
          - lessons/01_introduction-to-spatial.qmd
          - lessons/02_preprocessing-of-data.qmd
      
      - section: "Day 1 Self-learning:"
        contents:
          - lessons/03_quality-control.qmd
          - lessons/04_theory_of_PCA.qmd
          
      - section: "Day 2:"
        contents:
          - lessons/05_normalization.qmd
          - lessons/06_clustering.qmd
          
      - section: "Day 2 Self-learning"
        contents:
          - lessons/07_clustering-quality-control.qmd
          - lessons/08_marker-identification.qmd
          - lessons/09_integration.qmd
          
      - section: "Day 3:"
        contents:
          - lessons/10_spatially-derived-values.qmd
          - lessons/11_deconvolution.qmd

      - section: "Day 3 Self-learning"
        contents:
          - lessons/12_dge.qmd
          - lessons/Cheatsheet_seurat.qmd
      
      - section: "Day 4:"
        contents:
          - lessons/13_cell-cell-communication.qmd

format:
  html:
    theme: simplex
    css: css/styles.css
    fig-align: "center"
    toc: true
    number-sections: false
    code-block-bg: true
    code-copy: true      # enables copy button (default in most themes)
    code-tools: true     # enables the copy button!
    code-line-wrap: wrap
    google-analytics: UA-150953419-1
    prompt: true
    self-contained: true

# Global Execution Defaults
execute:
  echo: true               # show code
  eval: true               # run code
  warning: false           # show warnings
  error: false             # show errors
  message: false           # show messages
  prompt: true
